# Generated by Django 2.0.1 on 2018-02-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_sched', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='org',
            field=models.CharField(default='Your org. here', max_length=254),
        ),
    ]
